app_id: "e4f66fdd-5a05-49fe-b1c7-ebda5a2a5341"
app_secret: "y50u:Ciil[Rd]vEOHc?JJ6Dc3dDlPQxF"
redirect: "http://localhost:8000/tutorial/callback"
scopes: "openid profile offline_access user.read calendars.read"
authority: "https://login.microsoftonline.com/common"
authorize_endpoint: "/oauth2/v2.0/authorize"
token_endpoint: "/oauth2/v2.0/token"